language: node_js
node_js:
- 8.9.1

script: ng build --project ng-bootstrap-form-validation

before_deploy: "scripts/travis-deploy-setup.sh && cd dist"

deploy:
  - provider: npm
    skip_cleanup: true
    email: kevin.kipp@gmail.com
    api_key:
      secure: NnpDdb2vkN5MObg3kXrhEZqzSbgEgV5tDVEqggP/u9KsdXvUoF9ECXT2+A9pHLv5EdmZtbCiUjsEHJTClEPJosduVREmzXwbSCOHVMEkNu2kt8lHNniRAiBRS//XtCGaeD5NoX2OltGC2EOx1DDToyfBvUJI9AsC/ZpAzxsvEvQM4I2SMQF8W2HXKWMZIkOIbYBmN7MRLDufERkzX0cQqFrN1xZ0CGynwaeI4h08vX79A7nVRYRg0fwLpeDVXHWSt4cu41wyX1ei9IyDI43JDdp449SXZS8iMXPyNNlzjHRuIYkxtj1KvJTSBd7yDaiFhO/Mxj4pV6ftBFOJZI3PC8TwX920DWczWEo0X7kzMrUNxvbTEf2Wfw6Djwlon06hCj3bz6IyKBuliK4DyN2XZU3pZt624iajCuKwW3Y+k23DfHqgbQv73stTlvHfIrG4om14KOzuc60mepQWhyyX5r4GChN2o870Tz2T89gjrwrhS7YYXC0Cn+0AYTbxGKSQvFGj0ZzxaYp/tJ3N3sT0+JwFdKmNohLy5v5Af3fuUtzbiJrSboYwu+7TdVb8yH3RgqJ9npzi0MZB2Z2WcXn0x+Ofp7FiRDtq+2dbP8ukvZf/iFmqG0w5LqVadynAYr+mREeCWy/44yVu6CU8ikhlI4XgC7yZ02o5ia3nL8Gl9uI=
    on:
      tags: true
      repo: third774/ng-bootstrap-form-validation
  - provider: npm
    skip_cleanup: true
    tag: next
    email: kevin.kipp@gmail.com
    api_key:
      secure: NnpDdb2vkN5MObg3kXrhEZqzSbgEgV5tDVEqggP/u9KsdXvUoF9ECXT2+A9pHLv5EdmZtbCiUjsEHJTClEPJosduVREmzXwbSCOHVMEkNu2kt8lHNniRAiBRS//XtCGaeD5NoX2OltGC2EOx1DDToyfBvUJI9AsC/ZpAzxsvEvQM4I2SMQF8W2HXKWMZIkOIbYBmN7MRLDufERkzX0cQqFrN1xZ0CGynwaeI4h08vX79A7nVRYRg0fwLpeDVXHWSt4cu41wyX1ei9IyDI43JDdp449SXZS8iMXPyNNlzjHRuIYkxtj1KvJTSBd7yDaiFhO/Mxj4pV6ftBFOJZI3PC8TwX920DWczWEo0X7kzMrUNxvbTEf2Wfw6Djwlon06hCj3bz6IyKBuliK4DyN2XZU3pZt624iajCuKwW3Y+k23DfHqgbQv73stTlvHfIrG4om14KOzuc60mepQWhyyX5r4GChN2o870Tz2T89gjrwrhS7YYXC0Cn+0AYTbxGKSQvFGj0ZzxaYp/tJ3N3sT0+JwFdKmNohLy5v5Af3fuUtzbiJrSboYwu+7TdVb8yH3RgqJ9npzi0MZB2Z2WcXn0x+Ofp7FiRDtq+2dbP8ukvZf/iFmqG0w5LqVadynAYr+mREeCWy/44yVu6CU8ikhlI4XgC7yZ02o5ia3nL8Gl9uI=
    on:
      branch: master
      repo: third774/ng-bootstrap-form-validation
